function [Buy_rate, Sell_rate] = getBuySellrate(start_date,resolution,time_horizon,TOU_CHOICE)
    
    start_date = datetime(start_date); % Convert type from (str=>datetime)
    t1 = start_date; 
    t2 = t1 + minutes(time_horizon);   % Calculate end datetime
  
    vect = t1:minutes(resolution):t2; 
    vect(end) = []; vect = vect';
    vechour = hour(vect);
    currency_conversion = 0.0298; % THB to USD

    switch TOU_CHOICE
        case 'smart1'

        % Buy_rate = 2*(vechour >= 0  & vechour <  10)+...
        %            3*(vechour >= 10 & vechour <= 14)+...
        %            5*(vechour >  14 & vechour <  18)+...
        %            7*(vechour >= 18 & vechour <= 22)+...
        %            2*(vechour >  22 & vechour <= 23);
        Buy_rate = 2.7*(vechour >= 0  & vechour <  10)+...
           5.7*(vechour >= 10 & vechour <= 14)+...
           7*(vechour >  14 & vechour <  18)+...
           8*(vechour >= 18 & vechour <= 22)+...
           2.7*(vechour >  22 & vechour <= 23);
        
        % Sell_rate = 2*ones(length(vechour),1); 
        % Sell_rate(vechour >= 18 & vechour <= 22) = 2.5 ;

        Sell_rate = 2.2*ones(length(vechour),1); 
        Sell_rate(vechour >= 18 & vechour <= 22) = 2.5 ;

        % Convert THB to USD (11 April)
        Buy_rate = Buy_rate * currency_conversion; 
        Sell_rate = Sell_rate * currency_conversion;

        case 'nosell'
        % buyrate is just like case 'smart1' but customers cannot sell the power
        Buy_rate = 2*(vechour >= 0  & vechour <  10)+...
                   3*(vechour >= 10 & vechour <= 14)+...
                   5*(vechour >  14 & vechour <  18)+...
                   7*(vechour >= 18 & vechour <= 22)+...
                   2*(vechour >  22 & vechour <= 23);
        Sell_rate = zeros(length(vechour),1); 

        % Convert THB to USD 11 April
        Buy_rate = Buy_rate * currency_conversion; 

        case 'THcurrent'
        % Current rate  (not smart), sell_rate = 2 THB flat, 
        % buy_rate = 5.8 THB during [9:00-23:00] and 2.6 THB otherwise
        Buy_rate = 5.8*(vechour >= 9 & vechour <= 23)+...
                   2.6*(vechour >= 0 & vechour < 9);
        Sell_rate = 2*ones(length(vechour),1);

        case 'test_buy_less_sell'
        % buy_rate = [0-10:00)     2THB, 
        %            [10:00-14:00] 3THB,
        %            (14:00-18:00) 5THB,
        %            [18:00-22:00] 7THB,
        %            (22:00-24:00) 2THB
        % sell_rate = [18:00-22:00] 2.5THB and 2THB all other
        % times

        Buy_rate = 2*(vechour >= 0  & vechour <  10)+...
                   3*(vechour >= 10 & vechour <= 14)+...
                   5*(vechour >  14 & vechour <  18)+...
                   7*(vechour >= 18 & vechour <= 22)+...
                   2*(vechour >  22 & vechour <= 23);
        Sell_rate = 1*(vechour >= 0  & vechour <  10)+...
                   4*(vechour >= 10 & vechour <= 14)+...
                   4.5*(vechour >  14 & vechour <  18)+...
                   6*(vechour >= 18 & vechour <= 22)+...
                   3*(vechour >  22 & vechour <= 23);

        case 'test_buy_greater_sell'
        % buy_rate = [0-10:00)     2THB, 
        %            [10:00-14:00] 3THB,
        %            (14:00-18:00) 5THB,
        %            [18:00-22:00] 7THB,
        %            (22:00-24:00) 2THB
        % sell_rate = [18:00-22:00] 2.5THB and 2THB all other
        % times

        Buy_rate = 2*(vechour >= 0  & vechour <  10)+...
                   3*(vechour >= 10 & vechour <= 14)+...
                   5*(vechour >  14 & vechour <  18)+...
                   7*(vechour >= 18 & vechour <= 22)+...
                   2*(vechour >  22 & vechour <= 23);
        Sell_rate = 1*(vechour >= 0  & vechour <  10)+...
                   2.5*(vechour >= 10 & vechour <= 14)+...
                   4.5*(vechour >  14 & vechour <  18)+...
                   6*(vechour >= 18 & vechour <= 22)+...
                   1.5*(vechour >  22 & vechour <= 23);
    end
end